baseURL = "http://passcode.fr/"
languageCode = "en-us"
title = "Ingress Decode Group"
theme = "capsule"
hasCJKLanguage = true
copyright = "&copy; 2018. All rights reserved."
canonifyurls = true
paginate = 15

PygmentsCodeFences = true
PygmentsStyle = "friendly"

staticDir = ["static"]

[taxonomies]
  tag = "tags"
  category = "categories"


[params]
  # Shown in the home page
  subtitle = "Just a website"
  brand = "Blackburn"
  googleAnalytics = "Your Google Analytics tracking ID"
  disqus = "Your Disqus shortname"
  # CSS name for highlight.js
  highlightjs = "androidstudio"
  highlightjs_extra_languages = ["yaml"]
  dateFormat = "02 Jan 2006, 15:04"
  # Include any custom CSS and/or JS files
  # (relative to /static folder)
  custom_css = ["css/my.css"]
  custom_js = ["js/my.js"]

  [params.piwikAnalytics]
    siteid = 2
    piwikroot = "//analytics.example.com/"

[menu]
  # Shown in the side menu.
  [[menu.main]]
    name = "Home"
    pre = "<i class='fa fa-home fa-fw'></i>"
    weight = 1
    identifier = "home"
    url = "/"
  [[menu.main]]
    name = "Anomaly"
    pre = "<i class='fa fa-briefcase fa-fw'></i>"
    weight = 2
    identifier = "anomaly"
    url = "/categories/anomalycode/"
  [[menu.main]]
    name = "WOTD"
    pre = "<i class='fa fa-heartbeat fa-fw'></i>"
    weight = 3
    identifier = "wotd"
    url = "/categories/wotdcode/"
  [[menu.main]]
    name = "Investigate"
    pre = "<i class='fa fa-heartbeat fa-fw'></i>"
    weight = 4
    identifier = "investigate"
    url = "/categories/blogcode/"
  [[menu.main]]
    name = "Tools"
    pre = "<i class='fa fa-wrench fa-fw'></i>"
    weight = 5
    identifier = "tools"
    url = "/tools/"

[social]
  # Link your social networking accounts to the side menu
  # by entering your username or ID.

  # Techie
  github = "enldecode"
